sudo: required
os: linux
language: minimal
addons:
  apt:
    packages:
    - docker-ce
git:
  depth: 4
services:
  - docker

before_install:
  - docker pull debian:stable-slim
  - docker pull lacledeslan/steamcmd:linux

script:
  - docker version
  - docker build --no-cache --tag lltest/gamesvr-warsow --tag lacledeslan/gamesvr-warsow --build-arg BUILDNODE=TravisCI --build-arg SOURCE_COMMIT="$TRAVIS_COMMIT" ./linux
  - docker run -it --rm lltest/gamesvr-warsow ./ll-tests/gamesvr-warsow.sh

notifications:
  slack:
    secure: BmEUmx1potMCFmEK+09fgtKQinJr1bPjV3YaIpJ/whx1/PGlm+1B1gowUv7+po+h/JhrIaPp8/Y7UGV49F4RMbeN8tvTFaiC62H5q/2VLzURC68Awcukbhj1QXv944LnR2KWJhaOLUkv7v+KYt1qGvbNm5cvuar+EmnS5RcB6gzlbFvU09WZNdSY4P1CKyAZnSRooMeCF1R4U76N35jRLWclL2hgr1cX9dzU8Gg37eXnc1rkAbhKo1giJyS9LcK2l8ozSmnqzINmoNxmL2PU9PGTPuhP76wiJJI7oGNo5DkFwJ1T28mb9egUFQ2IzN5F6Am8RRrs6s2QzEXVefkYiP71jP/EkGTWS4xYZuC+9vqj1PyqCGkWdYN02cLShFi4wKBMa7QEbXTKPfclgemvjfwt3SjUfY7ymud805YDOo28BgCBJnCXvzaBgouj9PjtpldQJTe/lJSPvXXRLZRI0qU962JaCM7ljAAxBPyJ37YHLvhQLrYWs/NfM5Zc6IHd5JKo45/i3SQmqOYDHTVU1b0ODGzRGUlHOLT3MRLWiDak2JO/yqySq8O6wgGIa1VK1+hYu4FCYiCfzDLFcaF9N78GT/lG+AJI8LokPl43buqj2u3eCZk8qkCQ7UmNTPRKZpIWz5mZ5NwN5l4dpwFggf6h+Y9dpI+3EILBtUA3Wco=

before_deploy:
  - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin;
deploy:
  provider: script
  script: docker push lacledeslan/gamesvr-warsow
  on:
    branch: master
after_deploy:
- curl -X POST https://hooks.microbadger.com/images/lacledeslan/gamesvr-warsow/$MICROBADGER_TOKEN
